os: linux
dist: xenial
language: node_js

notifications:
  email: false

git:
  submodules: false

jobs:
  include:
    - language: ruby
      rvm:
        - 2.3
      script:
        - bundle exec jekyll build
    - language: node_js
      node_js:
        - 14
        # Reenable later if doing more than linting (i.e., testing)
        # - 12
        # - 10
      script:
        - npm run eslint
